### ISSUE TITLE
USBtinViewer java8

### ISSUE THREAD

**Issue by serdigi** [EmbedME/USBtinViewer#6]
Hello;
I wish you success in your work. When I try to run the USBtin viewer program on win10 with java8.

I am getting the following errors.;

C:\>java -jar USBtinViewer_v1.3.1.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Could not
 load the jssc library: Couldn't load library library jssc
        at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:90)
        at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
        at USBtinViewer.initComponents(Unknown Source)
        at USBtinViewer.<init>(Unknown Source)
        at USBtinViewer$11.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

How do i solve this problem.

Kind regards.

**Comment by mehmetalianil** [comment]
I also bumped into this issue with MacOS M2 (ARM) Java8.
Can't try with older versions of Java, since ARM support is only recent.
